name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and deploy
        run: |
          # 构建Docker镜像
          docker build -t gambling-prediction-app-api .
          
          # 停止并移除旧容器
          docker stop gambling-prediction-app-api || true
          docker rm gambling-prediction-app-api || true
          
          # 启动新容器
          docker run -d \
            --name gambling-prediction-app-api \
            -p 8080:8000 \
            --env-file .env \
            gambling-prediction-app-api 